---
- name: Set up YOLO e-commerce platform
  hosts: localhost
  become: yes
  vars_files:
    - roles/vars/main.yml

  pre_tasks:
    - name: Include common setup tasks
      import_role:
        name: common
      tags:
        - common

    - name: Add GitHub to known_hosts
      known_hosts:
        name: github.com
        key: "{{ lookup('pipe', 'ssh-keyscan github.com') }}"
        path: /home/vagrant/.ssh/known_hosts

    - name: Remove old backend folder if it exists
      file:
        path: "{{ app_dir }}/backend"
        state: absent

    - name: Clone backend repo
      git:
        repo: "{{ github_repo }}"
        dest: "{{ app_dir }}/backend"
        version: "master"
        force: yes
        update: yes
      environment:
        GIT_SSH_COMMAND: "ssh -i /home/vagrant/.ssh/id_ed25519 -o StrictHostKeyChecking=no"
      tags:
        - backend

  roles:
    - role: docker
      tags: docker

    - role: mongodb
      tags: mongodb

    - role: backend
      tags: backend

    - role: frontend
      tags: frontend