Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Sync current folder
  config.vm.synced_folder ".", "/vagrant"

  # Forward VM ports to host machine
  config.vm.network "forwarded_port", guest: 5000, host: 5050  # backend
  config.vm.network "forwarded_port", guest: 3000, host: 8081    # frontend container listens on 80
end