Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Sync the current folder (IP3) with /vagrant inside the VM
  config.vm.synced_folder ".", "/vagrant"

  # Forward VM ports to host machine
  config.vm.network "forwarded_port", guest: 5000, host: 5050  # backend
  config.vm.network "forwarded_port", guest: 80, host: 8081    # frontend
end